# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumWebDriverBasics():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumWebDriverBasics(self):
    self.driver.get("https://www.wikipedia.org/")
    self.vars["webTitle"] = self.driver.title
    self.vars["webUrl"] = self.driver.execute_script("return window.location.href")
    print(str("The title is: self.vars["webTitle"]"))
    print(str("The URL is: self.vars["webUrl"]"))
    self.driver.close()
  
