# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTcoo3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tcoo3(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(1458, 695)
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    self.driver.find_element(By.ID, "input-sort").click()
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#input-sort > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".image .img-responsive").click()
    self.driver.find_element(By.ID, "button-cart").click()
    self.driver.execute_script("window.scrollTo(0,92.80000305175781)")